### ISSUE TITLE
Infinite redirect when Space in input

### ISSUE THREAD

**Issue by Vivalldi** [kitze/sizzy#67] opened 2017-05-23 03:45 UTC
The following url `vuejs.com` will auto correct to `vue js.com` on some computers. This causes Sizzy to enter an infinite redirect loop as it tries to resolve the bindings for the url with a space. 

Example of url generated that was force stopped `http://sizzy.co/?url=https%3A%2F%2Fhttps%3A%2F%2Fhttp%3A%2F%2Fhttp%3A%2F%2Fhttps%3A%2F%2Fhttps%3A%2F%2Fhttp%3A%2F%2Fhttp%3A%2F%2Fhttps%3A%2F%2Fhttps%3A%2F%2Fhttp%3A%2F%2Fhttp%3A%2F%2Fhttps%3A%2F%2Fhttps%3A%2F%2Fhttp%3A%2F%2Fhttp%3A%2F%2Fhttps%3A%2F%2Fvue%20js.com`

Formatted
`http://https://https://http://http://https://https://http://http://https://https://http://http://https://https://http://http://https://vue js.com`

**Comment by Vivalldi** [comment] 2017-05-23 04:05
While playing around with "illegal" characters I came across the following list of characters that create this loop. 

- `SPACE`
- `^`
- `{`
- `}`
- `|`
- `<`
- `>`
- `` ` ``

**Comment by kitze** [comment] 2017-05-23 08:46
Thanks @Vivalldi, not a priority issue but will be fixed eventually!

**Comment by kitze** [comment] 2017-05-23 20:20
Duplicate of #33 so i'll close this one

**Closed by kitze** 2017-05-23 20:21 UTC
